name: Update Lottery Results

on:
  schedule:
    # כל יום בחצות (23:59 בישראל ≈ 21:59 UTC)
    - cron: '59 21 * * *'
  workflow_dispatch: # אפשרות להרצה ידנית

jobs:
  update-lottery:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install playwright
        playwright install --with-deps chromium
    
    - name: Run lottery scraper
      run: |
        echo "Starting lottery scraper..."
        python lottery_scraper.py
    
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git diff --staged --quiet || git commit -m "Auto-update lottery results - $(date)"
        git push
